### PR TITLE
Add development tools to the image

### LINKED ISSUE #1: Molecule tests faill with missing gcc
# 🐛 Bug Report

Molecule tests using this image are now failing with: 
`FileNotFoundError: [Errno 2] No such file or directory: 'gcc'`

## To Reproduce

Install docker  and docker-compose using pip3:

https://github.com/cisagov/ansible-role-docker/blob/b8d02561cc46351c410dd19206ced2e546e3deb3/tasks/main.yml#L44-L49

## Expected behavior

Works like it used to. 

## Any helpful log output

https://github.com/cisagov/ansible-role-pca-gophish-composition/runs/754314059#step:7:376

```console
TASK [docker : Install docker-compose and the docker python library] ***********
fatal: [fedora33_systemd]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip3", "install", "docker[tls]", "docker-compose"], "msg": "stdout: Collecting docker[tls]
  Downloading docker-4.2.1-py2.py3-none-any.whl (143 kB)
Collecting docker-compose
  Downloading docker_compose-1.26.0-py2.py3-none-any.whl (139 kB)
Collecting six>=1.4.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting websocket-client>=0.32.0
  Downloading websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
Collecting requests!=2.18.0,>=2.14.2
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting pyOpenSSL>=17.5.0; extra == \"tls\"
  Downloading pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
Collecting idna>=2.0.0; extra == \"tls\"
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting cryptography>=1.3.4; extra == \"tls\"
  Using cached cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)
Collecting docopt<1,>=0.6.1
  Downloading docopt-0.6.2.tar.gz (25 kB)
Collecting jsonschema<4,>=2.5.1
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting cached-property<2,>=1.2.0
  Downloading cached_property-1.5.1-py2.py3-none-any.whl (6.0 kB)
Collecting PyYAML<6,>=3.10
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting dockerpty<1,>=0.4.1
  Downloading dockerpty-0.4.1.tar.gz (13 kB)
Collecting distro<2,>=1.5.0
  Downloading distro-1.5.0-py2.py3-none-any.whl (18 kB)
Collecting python-dotenv<1,>=0.13.0
  Downloading python_dotenv-0.13.0-py2.py3-none-any.whl (17 kB)
Collecting texttable<2,>=0.9.0
  Downloading texttable-1.6.2-py2.py3-none-any.whl (10 kB)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.4.5.2-py2.py3-none-any.whl (157 kB)
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.0.tar.gz (463 kB)

:stderr: WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-2ianh7ql/cffi/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-2ianh7ql/cffi/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\
'\"'\"', '\"'\"'\
'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6du2fbgc
         cwd: /tmp/pip-install-2ianh7ql/cffi/
    Complete output (43 lines):
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Traceback (most recent call last):
      File \"<string>\", line 1, in <module>
      File \"/tmp/pip-install-2ianh7ql/cffi/setup.py\", line 149, in <module>
        ask_supports_thread()
      File \"/tmp/pip-install-2ianh7ql/cffi/setup.py\", line 77, in ask_supports_thread
        config.try_compile('__thread int some_threadlocal_variable_42;'))
      File \"/usr/lib64/python3.9/distutils/command/config.py\", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File \"/usr/lib64/python3.9/distutils/command/config.py\", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File \"/usr/lib64/python3.9/distutils/ccompiler.py\", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File \"/usr/lib64/python3.9/distutils/unixccompiler.py\", line 126, in _compile
        self.spawn(compiler_so + cc_args + [src, '-o', obj] +
      File \"/usr/lib64/python3.9/distutils/ccompiler.py\", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File \"/usr/lib64/python3.9/distutils/spawn.py\", line 74, in spawn
        proc = subprocess.Popen(cmd, env=env)
      File \"/usr/lib64/python3.9/subprocess.py\", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File \"/usr/lib64/python3.9/subprocess.py\", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'gcc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
"}
```

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request adds the `dnf` group "Development Tools" to the image and closes #1.

## 💭 Motivation and Context

The "Development Tools" group, along with `python-devel` and `libffi-devel`, appear to be necessary for building `pip` modules now.

## 🧪 Testing

I rebuilt the image with these changes, pushed it to Docker Hub, and verified that [this GitHub Action](https://github.com/cisagov/ansible-role-pca-gophish-composition/runs/754592031) now passes.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by felddy — APPROVED** [review]
Thanks for fixing this.  💪 
Does this mean that our support of Fedora33 has some caveats that need to be documented?

**Comment by felddy** [comment]
I guess my question is... should those changes be propagated into the ansible roles themselves instead of the image?  Is this still a representative Fedora33 image?

**Review by dav3r — APPROVED** [review]
👍 but I defer to @jsf9k to answer @felddy's questions.

**Comment by jsf9k** [comment]
> guess my question is... should those changes be propagated into the ansible roles themselves instead of the image? Is this still a representative Fedora33 image?

An excellent question.  The image itself can't be built without these changes, so they are needed here.  I started this repo by cloning [geerlingguy/docker-fedora32-ansible](https://github.com/geerlingguy/docker-fedora32-ansible), but the foo I added is pretty much the same foo that exists in [geerlingguy/docker-debian10-ansible](https://github.com/geerlingguy/docker-debian10-ansible), for example.  In other words, I think it is as representative a Fedora 33 image as `geerlingguy/docker-debian10-ansible` is a representative Debian Buster image.  To answer your initial question, I think we are OK.

I do think that we should add `wheel` as a base pip dependency, so that when we have to build something for a package we build the wheel instead of running `setup.py`.  I will make that change, in `cisagov/skeleton-generic` right now.

**Pull request merged**
